### ISSUE TITLE
error in functional testing

### ISSUE THREAD

**Issue by xiadawei123** [Popgen48/scalepopgen#1]
### Description of the bug

Hello, I'm glad to hear that you came across your article in MBE and took the initiative to test the Scalepopgen workflow tool. After successfully installing it, I attempted to perform functional testing using the command "nextflow run scalepopgen_v1 -profile test,docker -qs 10". Unfortunately, it seems that the plugin cannot be downloaded. Upon checking the .nextflow.log file, it appears to be an issue with network connectivity preventing the download. How can I resolve this problem?

### Command used and terminal output

```console
nextflow run scalepopgen_v1 -profile test,docker -qs 10
terminal show as follow：
N E X T F L O W  ~  version 23.10.1
Launching `scalepopgen_v1/main.nf` [modest_einstein] DSL2 - revision: 40828e9270
ERROR ~ Cannot find latest version of nf-validation plugin

 -- Check '.nextflow.log' file for details
```

### Relevant files

[nextflow.log](https://github.com/Popgen48/scalepopgen/files/14744971/nextflow.log)

**Comment by xiadawei123** [comment]
For stability considerations, is it possible to download all workflows and then conduct offline or localized analysis?

**Comment by xiadawei123** [comment]
And，i want to use nf-core download <pipeline> to download the pipeline and config profiles, but I couldn't find any pipeline related to scalepopgen in the nf-core repository.

**Comment by BioInf2305** [comment]
> ### Description of the bug
> 
> Hello, I'm glad to hear that you came across your article in MBE and took the initiative to test the Scalepopgen workflow tool. After successfully installing it, I attempted to perform functional testing using the command "nextflow run scalepopgen_v1 -profile test,docker -qs 10". Unfortunately, it seems that the plugin cannot be downloaded. Upon checking the .nextflow.log file, it appears to be an issue with network connectivity preventing the download. How can I resolve this problem?
> ### Command used and terminal output
> 
> ```
> nextflow run scalepopgen_v1 -profile test,docker -qs 10
> terminal show as follow：
> N E X T F L O W  ~  version 23.10.1
> Launching `scalepopgen_v1/main.nf` [modest_einstein] DSL2 - revision: 40828e9270
> ERROR ~ Cannot find latest version of nf-validation plugin
> 
>  -- Check '.nextflow.log' file for details
> ```
> 
> ### Relevant files
> 
> [nextflow.log](https://github.com/Popgen48/scalepopgen/files/14744971/nextflow.log)
> ### System information
> 
> _No response_

Hello, the error in the log file is similar to that of described here: https://github.com/nf-core/atacseq/issues/305. This is most probably due to problem with internet connection. If you are still unable to install the plugins, try also the solutions mentioned here: https://github.com/nextflow-io/nextflow/discussions/4126.

**Comment by BioInf2305** [comment]
> For stability considerations, is it possible to download all workflows and then conduct offline or localized analysis?

There are options to run subset of workflows at the same time. For instance, if you run only ADMIXTURE workflow once, Nextflow will download all the necessary tools and dependencies for the first time and if you don't delete the "work" folder (specifically container folder--"mamba", "singularity", etc.) , it will use the same set of tools without downloading them again in the subsequent runs. So I think it should be possible to run the analysis/workflow offline but only after you have run them successfully at least once while connected to the internet. Hope this answers your question.

**Comment by BioInf2305** [comment]
> And，i want to use nf-core download to download the pipeline and config profiles, but I couldn't find any pipeline related to scalepopgen in the nf-core repository.

Unfortunately, this pipeline is not a part of the "nf-core" organization, so you cannot find it there. This pipeline is developed independently.

**Comment by BioInf2305** [comment]
Please run "nextflow run _scalepopgen_ -profile test,docker -qs 10" instead of "nextflow run _scalepopgen_v1_ -profile test,docker -qs 10"

**Comment by BioInf2305** [comment]
I suggest to close this issue as it is most likely not a problem of the pipeline (?)

**Comment by xiadawei123** [comment]
> I suggest to close this issue as it is most likely not a problem of the pipeline.

ok，thank you for your reply！ have a nice day
